### ISSUE TITLE
How load tokenizer and model after training ?

### ISSUE THREAD

**Issue by ByUnal** [sayef/fsner#10]
I have these files after training. How can I load the tokenizer and model for testing or inference ?

![image](https://user-images.githubusercontent.com/43930582/187167570-5bffa8ec-3526-4acf-b902-7165b38dac66.png)

**Comment by sayef** [comment]
I assume these files are inside a folder, let's say  "pretrained_model". Now please see the example in the readme and replace "sayef/fsner-bert-base-uncased" with "./pretraimed_model".

**Comment by ByUnal** [comment]
I see, I'll try. The other problem is, I'm getting this error while I'm trying to train model.
![image](https://user-images.githubusercontent.com/43930582/187615683-7b6c229e-355d-4f13-8079-ad13a69caf85.png)

**Comment by ByUnal** [comment]
Worked, thanks.
